Update releases.json with 5.36 and 5.38
StrawberryPerl/strawberryperl.com pull request #35
Opened 2023-07-20 15:41 UTC by stevieb9

I've partially [automated](https://github.com/stevieb9/berrybrew/blob/master/doc/Update%20Releases%20JSON.md) the task to make it easier for myself. Until the website is back under proper administration, I'll keep updating the file as new releases are put out.

This change allows `berrybrew` to include the new versions.

To do so, you must update the `download_url` option within `berrybrew`, then do a `fetch` to pull the latest list. After this has been done, `berrybrew available` will list the new versions, which you can then `install` and `switch` to.

    berrybrew options download_url https://raw.githubusercontent.com/stevieb9/strawberryperl.com/gh-pages/releases.json

2023-07-20 15:48 UTC, genio requested changes
It contains duplicates as far as archname/name/numver/version combination goes. They should be combined into the latest release for each combo

2023-07-20 21:50 UTC, stevieb9 commented
Good catch. It looks like it may be a copy/paste issue, but I'll verify tomorrow morning. In fact, I'll just update the script to gather the data, open the `releases.json` file directly, convert to perl, insert the data, and write it back out.

2023-07-20 22:44 UTC, stevieb9 commented
@genio I've fixed the erroneous duplicate entries. Please have another look.

2023-07-21 01:13 UTC, genio approved these changes

2023-07-21 01:34 UTC, merged